SmartphoneRentStore/Areas/Admin/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace SmartphoneRentStore.Areas.Admin.Controllers
{
    public class HomeController : AdminBaseController
    {
        public IActionResult DashBoard()
        {
            return View();
        }

        public async Task<IActionResult> ForReview()
        {
            return View();
        }
    }
}

SmartphoneRentStore/Areas/Admin/Controllers/RentController.cs
namespace SmartphoneRentStore.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using SmartphoneRentStore.Core.Contracts;


    public class RentController : AdminBaseController
    {
        private readonly IRentService rentService;

       
        public RentController(IRentService _rentService)
        {
            rentService = _rentService;
        }

       
        public async Task<IActionResult> All()
        {
            var model = await rentService.AllAsync();

            return View(model);
        }
    }
}

SmartphoneRentStore/Areas/Admin/Controllers/SmartphoneController.cs
using Microsoft.AspNetCore.Mvc;
using SmartphoneRentStore.Core.Contracts;
using SmartphoneRentStore.Core.Models.Admin;
using SmartphoneRentStore.Extensions;

namespace SmartphoneRentStore.Areas.Admin.Controllers
{
    public class SmartphoneController : AdminBaseController
    {
        private readonly ISmartphoneService smartphoneService;
        private readonly ISupplierService supplierService;

        public SmartphoneController(ISmartphoneService _smartphoneService, ISupplierService _supplierService)
        {
            smartphoneService = _smartphoneService;
            supplierService = _supplierService;
        }

        public async Task<IActionResult> Mine()
        {
            var userId = User.Id();
            var supplerId = await supplierService.GetSupplierIdAsync(userId) ?? 0;

            var mySmartphones = new MySmartphonesViewModel()
            {
                AddedSmartphones = await smartphoneService.AllSmartphonesBySupplierIdAsync(supplerId),
                RentedSmartphones = await smartphoneService.AllSmartphonesByUserIdAsync(userId)
            };   
            
            return View(mySmartphones);
        }

        [HttpGet]
        public async Task<IActionResult> Approve()
        {
            var model = await smartphoneService.GetUnApprovedAsync();

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Approve(int smartphoneId)
        { 
            await smartphoneService.ApproveSmartphoneAsync(smartphoneId);

            return RedirectToAction(nameof(Approve));
        }

    }
}

SmartphoneRentStore/Areas/Admin/Controllers/UserController.cs
namespace SmartphoneRentStore.Areas.Admin.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.Extensions.Caching.Memory;
    using SmartphoneRentStore.Core.Contracts;
    using SmartphoneRentStore.Core.Models.Admin.User;
    using static SmartphoneRentStore.Core.Constants.AdministratorConstants;


    public class UserController : AdminBaseController
    {
        private readonly IUserService userService;
        private readonly IMemoryCache memoryCache;

        public UserController(IUserService _userService, IMemoryCache _memoryCache)
        {
            userService = _userService;
            memoryCache = _memoryCache;
        }

        public async Task<IActionResult> All()
        {
            var model = memoryCache.Get<IEnumerable<UserServiceModel>>(UsersCacheKey);

            if (model == null || model.Any() == false) // if the cashe memory is null or empty, we will read it from the database
            {                                          // аnd it saves it in the cache to be there for next time
                model = await userService.AllAsync();
                var cacheOptions = new MemoryCacheEntryOptions().SetAbsoluteExpiration(TimeSpan.FromMinutes(5));

                memoryCache.Set(UsersCacheKey, model, cacheOptions); // key, value, options
            }

            

            return View(model);
        }
    }
}

SmartphoneRentStore/Controllers/HomeController.cs
namespace SmartphoneRentStore.Controllers
{
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using SmartphoneRentStore.Core.Contracts;
    using SmartphoneRentStore.Models;
    using System.Diagnostics;


    public class HomeController : BaseController
    {
        private readonly ILogger<HomeController> _logger;
        private readonly ISmartphoneService smartphoneService;

        public HomeController(
            ILogger<HomeController> logger,
            ISmartphoneService _smartphoneService)
        {
            _logger = logger;
            smartphoneService = _smartphoneService;
        }


        [AllowAnonymous] // don't need logg in 
        public async Task<IActionResult> Index()
        {
            var model = await smartphoneService.LastFourSmartphonesAsync();

            return View(model);
        }


        [AllowAnonymous] // don't need logg in 
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error(int statusCode)
        {
            if (statusCode == 400)
            { 
                return View("Error400");
            }

            if (statusCode == 400)
            {
                return View("Error401");
            }

            if (statusCode == 404)
            {
                return View("Error404");
            }


            return View();
        }
    }
}

SmartphoneRentStore/Areas/Admin/Views/Home/DashBoard.cshtml
@{
    ViewData["Title"] = "Dashboard";
}

@{
    ViewData["Title"] = "Home Page";
}

<div class="mt-4 p-5 bg-light text-center">
    <h2 class="display-4">Hello, Admin!</h2>
    <p class="lead mb-1 mt-3">
        This is your administrator area - you can <b>read</b>, <b>create</b>,
        <b>delete</b> and <b>edit</b> smartphones.
        <br />You can <b>rent</b> and <b>leave</b> the free ones, too!
    </p>
    <p class="lead mt-1">
        You can also see <b>all users and suppliers</b> and <b>all rents</b> in the system.
    </p>
    <hr class="my-4">
    <a asp-area="" asp-controller="Smartphone" asp-action="All"
       class="btn btn-primary btn-lg">All Smartphones</a>
    <span>  |   </span>
    <a asp-area="" asp-controller="Smartphone" asp-action="Add"
       class="btn btn-primary btn-lg">Add Smartphone</a>
    <span>  |   </span>
    <a asp-area="Admin" asp-controller="Smartphone" asp-action="Mine"
       class="btn btn-primary btn-lg">My Smartphone</a>
    <span>  |   </span>
    <a asp-area="Admin" asp-controller="Rent" asp-action="All"
       class="btn btn-primary btn-lg">All Rents</a>
    <span>  |   </span>
    <a asp-area="Admin" asp-controller="User" asp-action="All"
       class="btn btn-primary btn-lg">All Users</a>
</div>

SmartphoneRentStore/Areas/Admin/Views/Home/ForReview.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}